#!/bin/bash
set -x
mkdir -p ./include
if [ -f "../fllib/include/fllib.h" ]; then cp ../fllib/include/fllib.h ./include/ ; fi
mkdir -p ./lib/fllib/linux-bash/x86_64/gcc/clang-debug
if [ -f "../fllib/build/linux-bash/x86_64/gcc/clang-debug/libfl.a" ]; then             cp  ../fllib/build/linux-bash/x86_64/gcc/clang-debug/libfl.a                            ./lib/fllib/linux-bash/x86_64/gcc/clang-debug/ ;                            fi
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/build/action.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/build/action.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/build/archive.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/build/archive.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/build/build.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/build/build.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/build/compile.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/build/compile.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/build/executable.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/build/executable.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/build/shared.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/build/shared.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/cli/args.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/cli/args.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/cli/cli.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/cli/cli.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/cli/cmdbuild.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/cli/cmdbuild.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/cli/cmdhelp.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/cli/cmdhelp.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/cli/cmdinit.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/cli/cmdinit.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/cli/cmdlist.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/cli/cmdlist.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/cli/cmdrun.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/cli/cmdrun.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/common/common.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/common/common.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/common/result.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/common/result.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/context.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/context.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/executor.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/executor.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/host.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/host.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/io.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/io.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/main.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/main.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/objects/action.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/objects/action.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/objects/configuration.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/objects/configuration.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/objects/environment.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/objects/environment.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/objects/for.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/objects/for.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/objects/preset.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/objects/preset.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/objects/target.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/objects/target.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/objects/toolchain.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/objects/toolchain.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/parser/action.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/action.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/parser/configuration.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/configuration.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/parser/environment.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/environment.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/parser/file.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/file.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/parser/for.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/for.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/parser/helpers.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/helpers.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/parser/lexer.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/lexer.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/parser/parser.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/parser.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/parser/preset.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/preset.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/parser/target.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/target.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/parser/toolchain.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/toolchain.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc  -I../fllib/include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c ./src/parser/variable.c -o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/variable.o -fPIC -ggdb -O0 -DFL_DEBUG 
gcc -o build/linux-bash/x86_64/gcc/clang-debug/sbs   obj/linux-bash/x86_64/gcc/clang-debug/src/build/action.o obj/linux-bash/x86_64/gcc/clang-debug/src/build/archive.o obj/linux-bash/x86_64/gcc/clang-debug/src/build/build.o obj/linux-bash/x86_64/gcc/clang-debug/src/build/compile.o obj/linux-bash/x86_64/gcc/clang-debug/src/build/executable.o obj/linux-bash/x86_64/gcc/clang-debug/src/build/shared.o obj/linux-bash/x86_64/gcc/clang-debug/src/cli/args.o obj/linux-bash/x86_64/gcc/clang-debug/src/cli/cli.o obj/linux-bash/x86_64/gcc/clang-debug/src/cli/cmdbuild.o obj/linux-bash/x86_64/gcc/clang-debug/src/cli/cmdhelp.o obj/linux-bash/x86_64/gcc/clang-debug/src/cli/cmdinit.o obj/linux-bash/x86_64/gcc/clang-debug/src/cli/cmdlist.o obj/linux-bash/x86_64/gcc/clang-debug/src/cli/cmdrun.o obj/linux-bash/x86_64/gcc/clang-debug/src/common/common.o obj/linux-bash/x86_64/gcc/clang-debug/src/common/result.o obj/linux-bash/x86_64/gcc/clang-debug/src/context.o obj/linux-bash/x86_64/gcc/clang-debug/src/executor.o obj/linux-bash/x86_64/gcc/clang-debug/src/host.o obj/linux-bash/x86_64/gcc/clang-debug/src/io.o obj/linux-bash/x86_64/gcc/clang-debug/src/main.o obj/linux-bash/x86_64/gcc/clang-debug/src/objects/action.o obj/linux-bash/x86_64/gcc/clang-debug/src/objects/configuration.o obj/linux-bash/x86_64/gcc/clang-debug/src/objects/environment.o obj/linux-bash/x86_64/gcc/clang-debug/src/objects/for.o obj/linux-bash/x86_64/gcc/clang-debug/src/objects/preset.o obj/linux-bash/x86_64/gcc/clang-debug/src/objects/target.o obj/linux-bash/x86_64/gcc/clang-debug/src/objects/toolchain.o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/action.o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/configuration.o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/environment.o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/file.o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/for.o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/helpers.o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/lexer.o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/parser.o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/preset.o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/target.o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/toolchain.o obj/linux-bash/x86_64/gcc/clang-debug/src/parser/variable.o ./lib/fllib/linux-bash/x86_64/gcc/clang-debug/libfl.a -lm -lpthread 
