mkdir obj\\x86_64 
if not exist .\\include (md .\\include)
if exist ..\\fllib\\include\\fllib.h (copy ..\\fllib\\include\\fllib.h .\\include\\)
if not exist .\\lib\\fllib\\win-cmd\\x86_64\\clang\\clang-debug (md .\\lib\\fllib\\win-cmd\\x86_64\\clang\\clang-debug)
if exist ..\\fllib\\build\\win-cmd\\x86_64\\clang\\clang-debug\\libfl.lib (copy ..\\fllib\\build\\win-cmd\\x86_64\\clang\\clang-debug\\libfl.lib .\\lib\\fllib\\win-cmd\\x86_64\\clang\\clang-debug\\)
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\build\action.c -o obj\win-cmd\x86_64\clang\clang-debug\src\build\action.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\build\archive.c -o obj\win-cmd\x86_64\clang\clang-debug\src\build\archive.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\build\build.c -o obj\win-cmd\x86_64\clang\clang-debug\src\build\build.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\build\compile.c -o obj\win-cmd\x86_64\clang\clang-debug\src\build\compile.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\build\executable.c -o obj\win-cmd\x86_64\clang\clang-debug\src\build\executable.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\build\shared.c -o obj\win-cmd\x86_64\clang\clang-debug\src\build\shared.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\cli\args.c -o obj\win-cmd\x86_64\clang\clang-debug\src\cli\args.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\cli\cli.c -o obj\win-cmd\x86_64\clang\clang-debug\src\cli\cli.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\cli\cmdbuild.c -o obj\win-cmd\x86_64\clang\clang-debug\src\cli\cmdbuild.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\cli\cmdhelp.c -o obj\win-cmd\x86_64\clang\clang-debug\src\cli\cmdhelp.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\cli\cmdinit.c -o obj\win-cmd\x86_64\clang\clang-debug\src\cli\cmdinit.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\cli\cmdlist.c -o obj\win-cmd\x86_64\clang\clang-debug\src\cli\cmdlist.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\cli\cmdrun.c -o obj\win-cmd\x86_64\clang\clang-debug\src\cli\cmdrun.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\common\common.c -o obj\win-cmd\x86_64\clang\clang-debug\src\common\common.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\common\result.c -o obj\win-cmd\x86_64\clang\clang-debug\src\common\result.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\context.c -o obj\win-cmd\x86_64\clang\clang-debug\src\context.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\executor.c -o obj\win-cmd\x86_64\clang\clang-debug\src\executor.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\host.c -o obj\win-cmd\x86_64\clang\clang-debug\src\host.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\io.c -o obj\win-cmd\x86_64\clang\clang-debug\src\io.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\main.c -o obj\win-cmd\x86_64\clang\clang-debug\src\main.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\objects\action.c -o obj\win-cmd\x86_64\clang\clang-debug\src\objects\action.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\objects\configuration.c -o obj\win-cmd\x86_64\clang\clang-debug\src\objects\configuration.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\objects\environment.c -o obj\win-cmd\x86_64\clang\clang-debug\src\objects\environment.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\objects\for.c -o obj\win-cmd\x86_64\clang\clang-debug\src\objects\for.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\objects\preset.c -o obj\win-cmd\x86_64\clang\clang-debug\src\objects\preset.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\objects\target.c -o obj\win-cmd\x86_64\clang\clang-debug\src\objects\target.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\objects\toolchain.c -o obj\win-cmd\x86_64\clang\clang-debug\src\objects\toolchain.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\parser\action.c -o obj\win-cmd\x86_64\clang\clang-debug\src\parser\action.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\parser\configuration.c -o obj\win-cmd\x86_64\clang\clang-debug\src\parser\configuration.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\parser\environment.c -o obj\win-cmd\x86_64\clang\clang-debug\src\parser\environment.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\parser\file.c -o obj\win-cmd\x86_64\clang\clang-debug\src\parser\file.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\parser\for.c -o obj\win-cmd\x86_64\clang\clang-debug\src\parser\for.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\parser\helpers.c -o obj\win-cmd\x86_64\clang\clang-debug\src\parser\helpers.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\parser\lexer.c -o obj\win-cmd\x86_64\clang\clang-debug\src\parser\lexer.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\parser\parser.c -o obj\win-cmd\x86_64\clang\clang-debug\src\parser\parser.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\parser\preset.c -o obj\win-cmd\x86_64\clang\clang-debug\src\parser\preset.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\parser\target.c -o obj\win-cmd\x86_64\clang\clang-debug\src\parser\target.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\parser\toolchain.c -o obj\win-cmd\x86_64\clang\clang-debug\src\parser\toolchain.o -ggdb -O0 -DFL_DEBUG 
clang  -I..\fllib\include  -std=c99 -Wall -Werror -Wextra -pedantic -Wmissing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-missing-braces -fstrict-aliasing -Wvla -finput-charset=UTF-8 -fexec-charset=UTF-8 -D_FORTIFY_SOURCE=2 -c .\src\parser\variable.c -o obj\win-cmd\x86_64\clang\clang-debug\src\parser\variable.o -ggdb -O0 -DFL_DEBUG 
link.exe /OUT:build\win-cmd\x86_64\clang\clang-debug\sbs.exe /DEFAULTLIB:libcmt.lib /NOLOGO /SUBSYSTEM:CONSOLE /DEBUG:FULL   obj\win-cmd\x86_64\clang\clang-debug\src\build\action.o obj\win-cmd\x86_64\clang\clang-debug\src\build\archive.o obj\win-cmd\x86_64\clang\clang-debug\src\build\build.o obj\win-cmd\x86_64\clang\clang-debug\src\build\compile.o obj\win-cmd\x86_64\clang\clang-debug\src\build\executable.o obj\win-cmd\x86_64\clang\clang-debug\src\build\shared.o obj\win-cmd\x86_64\clang\clang-debug\src\cli\args.o obj\win-cmd\x86_64\clang\clang-debug\src\cli\cli.o obj\win-cmd\x86_64\clang\clang-debug\src\cli\cmdbuild.o obj\win-cmd\x86_64\clang\clang-debug\src\cli\cmdhelp.o obj\win-cmd\x86_64\clang\clang-debug\src\cli\cmdinit.o obj\win-cmd\x86_64\clang\clang-debug\src\cli\cmdlist.o obj\win-cmd\x86_64\clang\clang-debug\src\cli\cmdrun.o obj\win-cmd\x86_64\clang\clang-debug\src\common\common.o obj\win-cmd\x86_64\clang\clang-debug\src\common\result.o obj\win-cmd\x86_64\clang\clang-debug\src\context.o obj\win-cmd\x86_64\clang\clang-debug\src\executor.o obj\win-cmd\x86_64\clang\clang-debug\src\host.o obj\win-cmd\x86_64\clang\clang-debug\src\io.o obj\win-cmd\x86_64\clang\clang-debug\src\main.o obj\win-cmd\x86_64\clang\clang-debug\src\objects\action.o obj\win-cmd\x86_64\clang\clang-debug\src\objects\configuration.o obj\win-cmd\x86_64\clang\clang-debug\src\objects\environment.o obj\win-cmd\x86_64\clang\clang-debug\src\objects\for.o obj\win-cmd\x86_64\clang\clang-debug\src\objects\preset.o obj\win-cmd\x86_64\clang\clang-debug\src\objects\target.o obj\win-cmd\x86_64\clang\clang-debug\src\objects\toolchain.o obj\win-cmd\x86_64\clang\clang-debug\src\parser\action.o obj\win-cmd\x86_64\clang\clang-debug\src\parser\configuration.o obj\win-cmd\x86_64\clang\clang-debug\src\parser\environment.o obj\win-cmd\x86_64\clang\clang-debug\src\parser\file.o obj\win-cmd\x86_64\clang\clang-debug\src\parser\for.o obj\win-cmd\x86_64\clang\clang-debug\src\parser\helpers.o obj\win-cmd\x86_64\clang\clang-debug\src\parser\lexer.o obj\win-cmd\x86_64\clang\clang-debug\src\parser\parser.o obj\win-cmd\x86_64\clang\clang-debug\src\parser\preset.o obj\win-cmd\x86_64\clang\clang-debug\src\parser\target.o obj\win-cmd\x86_64\clang\clang-debug\src\parser\toolchain.o obj\win-cmd\x86_64\clang\clang-debug\src\parser\variable.o .\lib\fllib\win-cmd\x86_64\clang\clang-debug\libfl.lib 
